# nixpacks.toml
[phases.setup]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["python backend/setup_db.py"]

[start]
cmd = "cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT"